# version: "3.9"

services:
  java_app:
    container_name: java_app
    image: mayadagjs/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - spring_datasource_url=jdbc:postgresql://java_db:5432/postgres
      - spring_datasource_username=${DB_USER}
      - spring_datasource_password=${DB_PASSWORD}
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
# commands
#m mvn clean package -DskipTests
# docker-compose --env-file .env  up -d

# Build a CRUD Rest API in Java using Spring boot, Hibernate, Postgres, Docker and Docker Compose
